const express=require('express');
const mongoose=require('mongoose');
const User=require('../models/User');
const Order=require('../models/Order');
const ReturnRequest=require('../models/ReturnRequest');
const {requireUser,requireCsrf}=require('../middlewares/auth');
const {asyncHandler,ok,AppError}=require('../utils/http');
const {normalizeMobile}=require('../utils/formatters');
const S=require('../services/serializers');
const router=express.Router();
router.use(requireUser);

function ownedOrderQuery(userId,id){const conditions=[{orderNumber:String(id)}];if(mongoose.isValidObjectId(id))conditions.push({_id:id});return{user:userId,$or:conditions};}
function addressPayload(body={}){return{title:String(body.title||'آدرس من').trim(),firstName:String(body.firstName||'').trim(),lastName:String(body.lastName||'').trim(),mobile:normalizeMobile(body.mobile),province:String(body.province||'').trim(),city:String(body.city||'').trim(),postalCode:String(body.postalCode||'').replace(/\D/g,''),buildingNumber:String(body.buildingNumber||'').trim(),unit:String(body.unit||'').trim(),address:String(body.address||'').trim(),isDefault:Boolean(body.isDefault)};}
function validateAddress(a){if(!a.firstName||!a.lastName||!/^09\d{9}$/.test(a.mobile)||!a.province||!a.city||!/^[0-9]{10}$/.test(a.postalCode)||!a.buildingNumber||a.address.length<10)throw new AppError(400,'اطلاعات آدرس کامل یا معتبر نیست');}

router.get('/',asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);const [orders,returns]=await Promise.all([Order.find({user:user._id}).sort({createdAt:-1}),ReturnRequest.find({user:user._id}).sort({createdAt:-1})]);ok(res,{user:S.user(user),orders:orders.map(S.order),returns:returns.map(r=>({id:r.publicId,orderId:String(r.order),orderNumber:r.orderNumber,productId:r.productId,type:r.requestType,status:r.status,reason:r.reason,note:r.note,createdAt:r.createdAt}))});}));
router.patch('/',requireCsrf,asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);for(const key of ['firstName','lastName','email','birthday','gender'])if(req.body[key]!==undefined)user[key]=String(req.body[key]||'').trim();await user.save();ok(res,{profile:S.user(user)});}));
router.patch('/notifications',requireCsrf,asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);user.notifications={sms:req.body.sms!==false,offers:req.body.offers!==false,restock:req.body.restock!==false};await user.save();ok(res,{preferences:user.notifications});}));

router.get('/addresses',asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);ok(res,{addresses:S.user(user).addresses});}));
router.post('/addresses',requireCsrf,asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);if(user.addresses.length>=10)throw new AppError(400,'حداکثر ۱۰ آدرس قابل ذخیره است');const value=addressPayload(req.body);validateAddress(value);if(value.isDefault)user.addresses.forEach(a=>a.isDefault=false);user.addresses.push(value);if(user.addresses.length===1)user.addresses[0].isDefault=true;await user.save();const saved=user.addresses[user.addresses.length-1];ok(res,{address:S.user(user).addresses.find(a=>a.id===saved.publicId)},201);}));
router.patch('/addresses/:id',requireCsrf,asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);const address=user.addresses.find(a=>a.publicId===req.params.id||String(a._id)===req.params.id);if(!address)throw new AppError(404,'آدرس پیدا نشد');const value=addressPayload({...address.toObject(),...req.body});validateAddress(value);if(value.isDefault)user.addresses.forEach(a=>a.isDefault=false);Object.assign(address,value);await user.save();ok(res,{address:S.user(user).addresses.find(a=>a.id===address.publicId)});}));
router.delete('/addresses/:id',requireCsrf,asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);const before=user.addresses.length;user.addresses=user.addresses.filter(a=>a.publicId!==req.params.id&&String(a._id)!==req.params.id);if(user.addresses.length===before)throw new AppError(404,'آدرس پیدا نشد');if(user.addresses.length&&!user.addresses.some(a=>a.isDefault))user.addresses[0].isDefault=true;await user.save();ok(res,{deleted:true,addresses:S.user(user).addresses});}));

router.get('/orders',asyncHandler(async(req,res)=>{const orders=await Order.find({user:req.session.userId}).sort({createdAt:-1});ok(res,{orders:orders.map(S.order)});}));
router.get('/orders/:id',asyncHandler(async(req,res)=>{const order=await Order.findOne(ownedOrderQuery(req.session.userId,req.params.id));if(!order)throw new AppError(404,'سفارش پیدا نشد');ok(res,{order:S.order(order)});}));
router.post('/returns',requireCsrf,asyncHandler(async(req,res)=>{const order=await Order.findOne(ownedOrderQuery(req.session.userId,String(req.body.orderId||'')));if(!order)throw new AppError(404,'سفارش پیدا نشد');if(order.status!=='delivered')throw new AppError(400,'مرجوعی فقط برای سفارش تحویل‌شده قابل ثبت است');const item=order.items.find(i=>i.productId===String(req.body.productId));if(!item||item.returnEligible===false)throw new AppError(400,'محصول برای مرجوعی معتبر نیست');const reason=String(req.body.reason||'').trim();if(!reason)throw new AppError(400,'دلیل درخواست را مشخص کنید');const request=await ReturnRequest.create({user:req.session.userId,order:order._id,orderNumber:order.orderNumber,productId:item.productId,reason,requestType:String(req.body.type||req.body.requestType||'return'),note:String(req.body.description||req.body.note||'').trim()});ok(res,{request:{id:request.publicId,status:request.status,createdAt:request.createdAt}},201);}));
router.post('/wheel/spin',requireCsrf,asyncHandler(async(req,res)=>{const user=await User.findById(req.session.userId);const today=new Date().toISOString().slice(0,10);if(String(user.wheelLastDate||'')===today)throw new AppError(429,'امروز یک‌بار از چرخونه استفاده کرده‌اید');const rewards=[{id:'free-shipping',title:'ارسال رایگان',short:'ارسال رایگان',type:'shipping',value:0,code:'FREESHIP',condition:'ویژه ارسال استاندارد'},{id:'discount-10',title:'۱۰٪ تخفیف',short:'۱۰٪',type:'discount',value:10,code:'TOTO10',condition:'طبق شرایط کد تخفیف'},{id:'points-150',title:'۱۵۰ امتیاز توتو',short:'۱۵۰ امتیاز',type:'points',value:150,points:150,condition:'به موجودی باشگاه اضافه می‌شود'},{id:'discount-5',title:'۵٪ تخفیف',short:'۵٪',type:'discount',value:5,condition:'کد پاداش در حساب ثبت می‌شود'}];const reward=rewards[(String(user.mobile).split('').reduce((sum,d)=>sum+Number(d||0),0)+new Date().getDate())%rewards.length];if(reward.points)user.loyalty.points+=reward.points;user.wheelLastDate=today;await user.save();ok(res,{reward,issuedAt:new Date().toISOString(),claimId:`CLM-${Date.now()}`});}));
module.exports=router;
