import { products } from '../../data/mock-data.js';
import { customerGallerySamples, galleryStatusLabel } from '../../data/customer-gallery-data.js';
import { localStore } from '../core/storage.js';
import { icon, toPersianDigits } from '../core/utils.js';

const storageKey='toto-customer-gallery';
const getUploads=()=>localStore.get(storageKey,[]);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const galleryCard=item=>`<article class="customer-gallery-card"><img src="${item.image}" alt="${escapeHtml(item.productName)} به انتخاب ${escapeHtml(item.customerName)}" width="900" height="1100" loading="lazy"><div><span>${icon('user','icon icon--sm')} ${escapeHtml(item.customerName)}</span><h3>${escapeHtml(item.productName)}</h3><p>${escapeHtml(item.caption)}</p><small>${item.createdAt}</small></div></article>`;

const resizeImage=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('خواندن تصویر انجام نشد.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('فرمت تصویر قابل استفاده نیست.'));image.onload=()=>{const maxSide=1200,scale=Math.min(1,maxSide/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78));};image.src=reader.result;};reader.readAsDataURL(file);});

const myUploadsTemplate=uploads=>`<section class="gallery-my-uploads" id="my-gallery" aria-labelledby="my-gallery-title"><div class="section-heading"><div><p class="eyebrow">حساب مشتری</p><h2 id="my-gallery-title">عکس‌های ارسالی من</h2><p>وضعیت بررسی عکس‌هایی که برای گالری فرستاده‌اید.</p></div></div>${uploads.length?`<div class="gallery-submission-list">${uploads.map(item=>`<article><img src="${item.image}" alt="" width="90" height="110"><div><strong>${escapeHtml(item.productName)}</strong><span>${item.createdAt}</span><small class="gallery-status gallery-status--${item.status}">${galleryStatusLabel(item.status)}</small></div>${item.status!=='approved'?`<button class="text-button" type="button" data-delete-gallery="${item.id}">${icon('trash','icon icon--sm')} حذف</button>`:''}</article>`).join('')}</div>`:'<div class="mini-empty"><p>هنوز عکسی برای گالری نفرستاده‌اید.</p></div>'}</section>`;

export const initCustomerGallery=({toast})=>{const root=document.getElementById('customer-gallery-root');if(!root)return;let previewData='';
  const render=()=>{const uploads=getUploads(),approved=[...customerGallerySamples,...uploads.filter(item=>item.status==='approved')],session=localStore.get('toto-session',null);root.innerHTML=`<section class="gallery-hero"><div><p class="eyebrow">توتو به سبک شما</p><h1>گالری مشتریان</h1><p>استایل واقعی مشتریان توتو؛ عکس خودتان را هم بفرستید تا بعد از بررسی در این گالری منتشر شود.</p><a class="button" href="#share-look">ارسال عکس من</a></div><div class="gallery-hero__collage">${approved.slice(0,3).map(item=>`<img src="${item.image}" alt="" width="500" height="620">`).join('')}</div></section><section class="section gallery-showcase" aria-labelledby="gallery-showcase-title"><div class="section-heading"><div><p class="eyebrow">انتخاب‌های واقعی</p><h2 id="gallery-showcase-title">شما چطور توتو را می‌پوشید؟</h2></div><span class="soft-badge">${toPersianDigits(approved.length)} استایل منتشرشده</span></div><div class="customer-gallery-grid">${approved.map(galleryCard).join('')}</div></section><section class="section gallery-share" id="share-look" aria-labelledby="share-look-title"><div class="gallery-share__intro"><p class="eyebrow">سهم شما در گالری</p><h2 id="share-look-title">عکس استایلتان را بفرستید</h2><p>یک عکس روشن و واضح انتخاب کنید، محصول توتو را مشخص کنید و چند کلمه دربارهٔ استایلتان بنویسید.</p><ul><li>حداکثر حجم فایل ۸ مگابایت</li><li>فرمت JPG، PNG یا WebP</li><li>انتشار فقط پس از تأیید تیم محتوا</li></ul></div><form class="gallery-upload-form" id="gallery-upload-form" novalidate><div class="form-grid form-grid--2"><label class="field"><span>نام نمایشی</span><input class="input" name="customerName" maxlength="32" required value="${escapeHtml(session?.customer?.firstName||'')}"><small class="field-message"></small></label><label class="field"><span>محصول توتو</span><select class="input" name="productId" required><option value="">انتخاب محصول</option>${products.map(product=>`<option value="${product.id}">${product.name}</option>`).join('')}</select><small class="field-message"></small></label></div><label class="field"><span>داستان کوتاه استایل</span><textarea class="input" name="caption" rows="4" maxlength="220" placeholder="مثلاً این مانتو را برای یک روز کاری با شلوار روشن ست کردم..." required></textarea><small class="field-message"></small></label><label class="gallery-file-field" for="gallery-image"><span id="gallery-preview">${icon('image','icon icon--lg')}<strong>انتخاب عکس</strong><small>عکس را اینجا انتخاب کنید</small></span><input id="gallery-image" name="image" type="file" accept="image/jpeg,image/png,image/webp" required></label><label class="gallery-consent"><input type="checkbox" name="consent" required><span>اجازه می‌دهم این عکس با نام نمایشی من در گالری توتو منتشر شود.</span></label><div class="field-message field-message--error" id="gallery-form-error"></div><button class="button button--block" type="submit">ارسال برای بررسی</button></form></section>${myUploadsTemplate(uploads)}`;bind();};
  const bind=()=>{const form=document.getElementById('gallery-upload-form'),fileInput=document.getElementById('gallery-image');fileInput?.addEventListener('change',async()=>{const file=fileInput.files[0],error=document.getElementById('gallery-form-error');error.textContent='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){error.textContent='فرمت تصویر باید JPG، PNG یا WebP باشد.';fileInput.value='';return;}if(file.size>8*1024*1024){error.textContent='حجم تصویر بیشتر از ۸ مگابایت است.';fileInput.value='';return;}try{previewData=await resizeImage(file);document.getElementById('gallery-preview').innerHTML=`<img src="${previewData}" alt="پیش‌نمایش عکس انتخابی"><strong>تغییر عکس</strong>`;}catch(errorValue){error.textContent=errorValue.message;}});form?.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form)),error=document.getElementById('gallery-form-error');error.textContent='';if(!values.customerName?.trim()||!values.productId||!values.caption?.trim()){error.textContent='نام، محصول و توضیح استایل را کامل کنید.';return;}if(!previewData){error.textContent='لطفاً یک عکس انتخاب کنید.';return;}if(!form.elements.consent.checked){error.textContent='برای ارسال عکس، اجازهٔ انتشار را تأیید کنید.';return;}const product=products.find(item=>item.id===values.productId),entry={id:`gallery-${Date.now()}`,customerName:values.customerName.trim(),productId:values.productId,productName:product.name,caption:values.caption.trim(),image:previewData,status:'pending',createdAt:new Intl.DateTimeFormat('fa-IR').format(new Date())};try{if(!localStore.set(storageKey,[entry,...getUploads()]))throw new Error('storage');previewData='';toast('عکس شما ثبت شد و پس از بررسی در گالری نمایش داده می‌شود.');render();document.getElementById('my-gallery')?.scrollIntoView({behavior:'smooth'});}catch{error.textContent='فضای ذخیره‌سازی مرورگر کافی نیست؛ عکس کوچک‌تری انتخاب کنید.';}});root.querySelectorAll('[data-delete-gallery]').forEach(button=>button.addEventListener('click',()=>{localStore.set(storageKey,getUploads().filter(item=>item.id!==button.dataset.deleteGallery));toast('عکس ارسالی حذف شد.','info');render();}));};
  render();if(new URLSearchParams(location.search).get('mine')==='1')requestAnimationFrame(()=>document.getElementById('my-gallery')?.scrollIntoView());};
